### PR TITLE
Fix for Laravel 5.8

### PR DESCRIPTION
**Pull request by filippofortino**

### CODE REVIEW

**Comment by okaufmann** [comment]
+1

**Comment by Michael-Stokoe** [comment]
I was about to fork this and make this fix.

Time well saved :P

**Comment by filippofortino** [comment]
> I was about to fork this and make this fix.
> 
> Time well saved :P

I am actually not sure of what i did, i am not really experienced with Travis CI. I just edited some stuff until it worked. If you think you can do something better feel free to fork it and fix it :)

**Comment by ghost** [comment]
i made a fork and removed the Service Provider for Laravel4

**Comment by filippofortino** [comment]
> This is rly bad .... you force to use redis but you dont add it to composer as requirement. And the result is "Error - Class 'Predis\Client' not found". Most users want file cache.

Yeah, you're absolutely right, i made some changes for myself and accidentally added them to this pull request. I will close it.

**Pull request closed without merging**
