### PR TITLE
Laravel 6, 7, 8 support, drop support for 4, 5, upgrade to php-tmdb/api 3.0

### PR DESCRIPTION
**Pull request by leon0399**
Todo:

- [ ] Use Laravel Http Client
- [ ] Update README

### CODE REVIEW

**Comment by kertahayu** [comment]
When will this be merged?

**Comment by nexxai** [comment]
@dele-corporate I can't speak for the original contributor, but it's still in "Draft" status, so presumably some time after they decide that it's finished and ready to go?

**Comment by leon0399** [comment]
@dele-corporate  yeah, there are still some things to do, I'll try to find my time to finish all on weekend

**Comment by RomainGoncalves** [comment]
It would be awesome if this could get merged. Can we help @leon0399 ?

**Comment by leon0399** [comment]
> It would be awesome if this could get merged. Can we help @leon0399 ?

the only real thing left to do, is Readme and some final testing, but I simply can't find enough time to finish

**Comment by RomainGoncalves** [comment]
> > It would be awesome if this could get merged. Can we help @leon0399 ?
> 
> the only real thing left to do, is Readme and some final testing, but I simply can't find enough time to finish

Thanks for working on it. Hope you find time soon.

**Comment by nexxai** [comment]
@leon0399 Can you outline what you're still working on in case someone might want to help work with you on it?

**Comment by mattkloc** [comment]
I've been waiting for Laravel 8 support for sometime... Hope this PR gets merged soon! If you need any help as others have offered before please do not hesitate to ask!

Thanks for the hard work @leon0399!

**Comment by wtfzdotnet** [comment]
:wave: Hi there @leon0399 @RomainGoncalves @mattkloc @nexxai @dele-corporate :wave: 

I'm hard at work preparing for a new major release of `php-tmdb/api`, we are skipping `3.0` altogether and going for `4.0`. I have already done some work on the `php-tmdb/symfony` repository to prepare, however I've just spent most of the day just making the unit tests work with the new massive overhaul. Since laravel is not my expertise, it would be nice to have a big update coming for laravel at the same time everything else gets released.

I hope you can find the time to wrap this up against the `4.0` branch, I will be busy again somewhere this week to make the `HttpClient` and `Client` "stable". The current state of things for these low layer classes isn't something you should be basing off on right now.

Release will include;

- (Re-Implementation) of PSR-3
- Implementation of PSR-6
- Implementation of PSR-7
- Implementation of PSR-12
- Implementation of PSR-14
- Implementation of PSR-16
- Implementation of PSR-17
- Implementation of PSR-18
- Refactor of low level classes
- _Cleanup of tests, sort of, I might postpone this for 4.1_
- Dropping doctrine cache ( bring your own PSR-16 client )
- Dropping guzzle http ( bring your own PSR-18 client )
- New CI/CD integration ( github actions, as travis-ci is being abandoned )
- Code style checking
- Unit tests running on PHP 7.3, 7.4 and 8.0 ( still allowing failures as of now ), _everything under php 7.3 will be dropped_.

To keep an eye on the work in progress, see https://github.com/php-tmdb/api/pull/225 and https://github.com/php-tmdb/symfony/pull/29 respectively.

:christmas_tree:

**Comment by wtfzdotnet** [comment]
Take a look here if you want  to get a heads up of where abouts I am moving towards :-)

- https://github.com/php-tmdb/api/blob/release/4.0.0/lib/Tmdb/Client.php#L86
- https://github.com/php-tmdb/api/blob/release/4.0.0/lib/Tmdb/Client.php#L110

**Comment by wtfzdotnet** [comment]
You have a green light to go ahead, caching is still missing but I'll get that done by the end of this week.

I updated most of the documentation in `release/4.0.0` branch, so review that branch to get started. If something is unclear let me know. https://github.com/php-tmdb/api/pull/225

- Do not make choices for the end user by introducing for example a certain http client, instead try to align with the development dependencies of the api. If you want to default to the laravel http client, be my guest but make sure the configuration still allows any other client to be still injected.

For logging and caching, the options are removed in `4.0`, instead just register the corresponding listeners as per documentation.

**Comment by wtfzdotnet** [comment]
`4.0.0-alpha` dropped

- https://github.com/php-tmdb/api
- https://github.com/php-tmdb/symfony

Let me know if I have to clarify anything at all to help this pull request get up to date :-)

**Comment by n0v3xx** [comment]
Is this ready to use or testable anywhere?

**Pull request closed without merging**
